In [2]:
with open ("/Users/apple/Downloads/sentiment labelled sentences/amazon_cells_labelled.txt","r") as text_file:
    lines = text_file.read().split("\n")

In [3]:
with open ("/Users/apple/Downloads/sentiment labelled sentences/yelp_labelled.txt","r") as text_file:
    lines += text_file.read().split("\n")

In [4]:
with open ("/Users/apple/Downloads/sentiment labelled sentences/imdb_labelled.txt","r") as text_file:
    lines += text_file.read().split("\n")

In [5]:
lines =[line.split("\t") for line in lines if len(line.split("\t")) ==2 and line.split("\t")[1]]

In [6]:
train_documents = [line[0] for line in lines]

In [7]:
train_labels = [int(line[1]) for line in lines]

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
count_vectorizer = CountVectorizer(binary="True")

In [11]:
train_documents = count_vectorizer.fit_transform(train_documents)

In [12]:
train_documents

<3000x5155 sparse matrix of type '<class 'numpy.int64'>'
	with 31578 stored elements in Compressed Sparse Row format>

In [13]:
print (train_documents[0])

  (0, 1013)	1
  (0, 647)	1
  (0, 1982)	1
  (0, 4793)	1
  (0, 4835)	1
  (0, 4531)	1
  (0, 2158)	1
  (0, 2314)	1
  (0, 2432)	1
  (0, 3387)	1
  (0, 4609)	1
  (0, 2809)	1
  (0, 1829)	1
  (0, 4987)	1
  (0, 3043)	1
  (0, 2427)	1
  (0, 4545)	1
  (0, 4161)	1


In [14]:
from sklearn.naive_bayes import BernoulliNB

In [15]:
classifier = BernoulliNB().fit(train_documents, train_labels)

In [16]:
classifier.predict(count_vectorizer.transform(["This is the best movie"]))

array([1])

In [17]:
classifier.predict(count_vectorizer.transform(["This is the worst movie"]))

array([0])

In [18]:
classifier.predict(count_vectorizer.transform(["This is absurd"]))

array([1])

In [19]:
classifier.predict(count_vectorizer.transform(["This is pathetic"]))

array([0])

In [18]:
classifier.predict(count_vectorizer.transform(["This movie seems pretty good"]))

array([1])